services:
  backend:
    build: ./backend
    container_name: monke-backend
    restart: unless-stopped
    networks:
      - webnet

  frontend:
    container_name: monke-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet:
    external: true
