services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
